import assert from "node:assert/strict";
import test from "node:test";

import { postMessage } from "./messages.ts";

// Expected strings generated by api/social.py post_message.
const expected: string[] = ["unimap post\ndistrict: 840000.bitmap\nreply-to: none\nas: none\ntime: 1760000000\nmedia: none\n\ngm\nline 2", "unimap post\ndistrict: 5.bitmap\nreply-to: 12\nas: 7.bitmap\ntime: 1\nmedia: https://a/b.png\nmedia: https://c/d.png\n\nhi"];

test("post message matches the API", () => {
  assert.equal(postMessage(840000, null, null, 1760000000, [], "gm\nline 2"), expected[0]);
  assert.equal(postMessage(5, 12, 7, 1, ["https://a/b.png", "https://c/d.png"], "hi"), expected[1]);
});
